#236 - Ajuste de texto na criação de senha- Tray login
tray-tecnologia/tray-login pull request #108
Opened 2020-10-02 13:26 UTC by colomeramonica

## Contexto

**Por que essa mudança é necessária?**

Atualização da versão do Tray Login para correção do texto na criação de senha

**Como o problema foi atacado?**

Atualização da label no Tray Login sendo necessário a atualização da versão

**Quais os efeitos dessa implementação?**

Criação de senha com campos mais explicativos

**Quais os possíveis pontos de impacto dessa implementação?**

Recuperação de senha

**Esse merge request possui feature toggle? `NÃO`

## Critérios de aceite

* [x] - Approver: @lcaliani ou @igor.freitas
* [ ] - O código que eu adicionei está coberto
* [ ] - Um humano testou manualmente

#### Precisa limpar algum cache ? `NÃO`

2020-10-02 17:57 UTC, douglas-neves requested changes

2020-10-02 17:57 UTC, douglas-neves commented on src/components/TogglePassword.vue
> +      :placeholder="id === 'confirm-new-password' ?
Cria uma computed `label` pra essa regra, fica mais facil pra alterar depois.

2020-10-05 11:43 UTC, colomeramonica commented on src/components/TogglePassword.vue
> +      :placeholder="id === 'confirm-new-password' ?
Alterado

2020-10-05 12:19 UTC, douglas-neves approved these changes

2020-10-05 14:21 UTC, lcaliani approved these changes

2020-10-05 14:23 UTC, merged