#269 - Política de criação de senha (tray login)
tray-tecnologia/tray-login pull request #117
Opened 2021-04-26 19:31 UTC by colomeramonica

2021-04-29 14:18 UTC, kennyrafael commented on dist/trayLogin.common.js
> +  if (_typeof(params) === 'object' && !Array.isArray(params)) {
Para facilitar a leitura, poderia inserir essas condições em uma variável!

2021-04-29 14:18 UTC, kennyrafael commented on dist/trayLogin.common.js
> +  } else {
Utilizando early return dá para remover esse `else`

2021-04-29 14:19 UTC, colomeramonica commented on dist/trayLogin.common.js
> +  if (_typeof(params) === 'object' && !Array.isArray(params)) {
Esses arquivos são auto-gerados, não tenho controle sobre eles :/

2021-04-29 14:21 UTC, colomeramonica commented on dist/trayLogin.common.js
> +  } else {
Mesmo caso https://github.com/tray-tecnologia/tray-login/pull/117#discussion_r623098809

2021-04-29 14:33 UTC, kennyrafael commented on dist/trayLogin.common.js
> +  if (_typeof(params) === 'object' && !Array.isArray(params)) {
viajei, sorry...hahahah

2021-04-29 14:35 UTC, douglas-neves commented on src/screens/Login/screens/RecoverPassword/screens/New.vue
> +      <div class="col-md-12">
Você pode usar só `col` ao invés de `col-md-12`.
Da uma olhada se removendo as divs `col` e  `row` os elementos já não ficaram alinhadas

2021-04-29 14:35 UTC, douglas-neves commented on src/screens/Login/screens/RecoverPassword/screens/New.vue
> +      if (!this.checkRequirements()) {
A Ideia do metodo `checkRequirements` é excelente, acha que é possível centralizar essas outras regras de validação presentes no submit neste método ? 

Com as regras separadas o método `submit` ficará bem mais especifico.

2021-04-29 14:40 UTC, douglas-neves requested changes

2021-04-29 14:40 UTC, douglas-neves commented on package.json
> +    "@fortawesome/fontawesome": "^1.1.8",
Precisa atualizar a versão do tray-login aqui no package.json
https://github.com/tray-tecnologia/tray-login/blob/2e5dd7ee0262c77dd76ec38ba12188a5f4e29cbe/package.json#L3

2021-04-29 15:00 UTC, lcaliani requested changes

2021-04-29 15:02 UTC, lcaliani commented on package.json
>      "vue": "^2.5.22",
Deu certo de atualizar o vue?
Em caso positivo, acho que já compensa deixarmos aqui a versão mínima aceitável, que seria `^2.6.12`

2021-04-30 11:54 UTC, colomeramonica commented on src/screens/Login/screens/RecoverPassword/screens/New.vue
> +      <div class="col-md-12">
Feito!

2021-04-30 11:54 UTC, colomeramonica commented on src/screens/Login/screens/RecoverPassword/screens/New.vue
> +      if (!this.checkRequirements()) {
Você diz jogar as outras validações dentro desse método? Como cada uma dispara um erro diferente, acho melhor deixar do jeito que está (a menos que eu tenha entedido errado)

2021-04-30 12:43 UTC, lcaliani approved these changes

2021-04-30 13:18 UTC, douglas-neves approved these changes

2021-04-30 14:13 UTC, merged