#271 - Criando novo fluxo para senha fraca
tray-tecnologia/tray-login pull request #128
Opened 2022-01-14 12:49 UTC by gustavohubess

Feature relacionada ao card [#271](https://git.tray.net.br/commerce/central/-/issues/271)

foi criado um novo fluxo que encaminha o usuário a tela de troca de senha quando for autenticado e seua senha estiver drava

2022-01-28 18:49 UTC, lcaliani commented on src/api/mock/data/langs.json
> +            "compulsory-password-title": "Alterar senha",
Dúvida, essas langs, devem voltar da aplicação certo? Se sim, vamos precisar ajustar a app que o login consome primeiro, para ter as langs.

2022-01-28 18:49 UTC, lcaliani commented on src/mixins/utils.js
> +    getIconName(
Por padrão dos outros métodos e pelo tamanho da assinatura, o que acha de jogarmos em uma linha só? Ex:

```js
getIconName(validationRule) {
  return validationRule ? checkIcon : timesIcon;
}
```

2022-01-28 18:49 UTC, lcaliani commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +        @keyup.native="$event.keyCode !== 13 ? clearErrors() : $event.preventDefault()"
Sugestões:
- Separar essa lógica em um método para somente chamá-lo aqui
- Passar o número `13` em uma constante significativa com docblock também, para sabermos o que ele significa e facilitar reuso e manutenção

2022-01-28 18:50 UTC, lcaliani commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +        @keyup.native="$event.keyCode !== 13 ? clearErrors() : $event.preventDefault()"
Mesmo caso https://github.com/tray-tecnologia/tray-login/pull/128/files#r794769263

2022-01-28 18:51 UTC, lcaliani requested changes

2022-01-28 18:51 UTC, lcaliani commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +      // todo: o erro ta aqui
Comentário ficou sobrando aqui

2022-01-28 19:02 UTC, lcaliani commented on src/screens/Login/screens/Main.vue
> +        } else if (this.callback) {
Sugestão, para diminuir a complexidade do trecho, podemos usar _early return_, dessa forma também conseguimos retirar a necessidade do `else`, ex:

```js
        if (!this.isStrongPassword && !this.isTestIdentifier) {
          this.setSecurityCode(response.data.data.code);
          this.setScreen('CompulsoryPassword');
          return;
        } 
       
        if (this.callback) {
          this.redirect(this.callback, response.data.data.token);
          return response;
        }
```
OBS: Sugeri essa forma imaginando que, independente de qual `if` entrar, não vai precisar prosseguir para as linhas de baixo

2022-01-28 19:07 UTC, lcaliani commented
**Ponto importante:** Precisamos também alterar a versão do `package.json` da lib (junto com esse Pull Request ou em um próximo) antes de gerar a tag de release no github.

Se não fizermos isso, ao puxar a dependência com `yarn` podemos ter problema em baixar a versão nova.

A última versão foi a `2.0.19` - marcada tanto no `package.json` quanto na tag do projeto:
- Package: https://github.com/tray-tecnologia/tray-login/blob/master/package.json#L3
- Tag: https://github.com/tray-tecnologia/tray-login/tree/2.0.19

Acredito que, como se trata de nova funcionalidade, podemos jogar a versão para a segunda casa, ou seja, **`2.1.0`**

2022-01-31 12:36 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +        @keyup.native="$event.keyCode !== 13 ? clearErrors() : $event.preventDefault()"
- Foi adicionada a variável `enterKeyCode` aos _mixins_ do projeto para que fosse substituído o valor 13 em todos os arquivos que o usavam.
- Foi criado o método `isKeyupEnter` para substituir a lógica que estava no `@keyup.native`

2022-01-31 12:42 UTC, gustavohubess commented on src/api/mock/data/langs.json
> +            "compulsory-password-title": "Alterar senha",
Essas langs ainda não existem na plataforma.
Foi combinado de serem criadas no back-end antes de concluir a issue.

2022-01-31 12:45 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +      // todo: o erro ta aqui
Foi igualmente corrigido!

2022-01-31 13:23 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +        @keyup.native="$event.keyCode !== 13 ? clearErrors() : $event.preventDefault()"
Corrigido!

2022-01-31 13:38 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
> +    <app-compulsory-password v-if="screen === 'CompulsoryPassword'"
feito

2022-01-31 13:41 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
> +      const testIdentifiers = ['teste@tray.com.br', 'testepagamento@tray.net.br'];
Bem observado!
Foi realocada a função `isTestIdentifier` aos _mixins utils_ do projeto.

2022-01-31 13:47 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +      // todo: o erro ta aqui
Este comentário está na master do projeto
não sei exatamente de que erro ele se trata :face_with_monocle:

2022-01-31 14:06 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
> +        } else if (this.callback) {
foi atribuída solução sugerida!

2022-01-31 14:07 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +      // todo: o erro ta aqui
comentário removido!
nenhum erro aparente encontrado.

2022-01-31 16:53 UTC, gustavohubess commented on src/screens/Login/screens/CompulsoryPassword/Main.vue
> +     * Atualiza a senha
Feito docblock

2022-02-03 15:21 UTC, merged