commerce/central#371 - tray-login na nova página de login
tray-tecnologia/tray-login pull request #133
Opened 2022-04-22 18:28 UTC by gustavohubess

ISSUE: https://git.tray.net.br/commerce/central/-/issues/371

Foi adicionado o novo parâmetro `data-callback-post`, responsável por carregar os parâmetros que serão enviados no body do post `my-account/api/login`.

![image](https://user-images.githubusercontent.com/87497961/164772870-3827dbc6-e8ab-43f4-88b4-0ed8f412e1c7.png)

Esse parametro carrega os seguintes atributos:

```
id_evento=
redirecionar=
PHPSESSID=
frete=
loja=
origem=
login=
parceiro=
IdProd=
premiacao=
transID=
id_pedido=
```

Há uma nova requisição após o validar o e-mail e senha. O post para `my-account/api/login` retorna um token e um link de redirecionamento.

![image](https://user-images.githubusercontent.com/87497961/164773235-31c0d8ce-c543-4eb1-9d94-6f94f86a22af.png)

2022-04-22 19:45 UTC, lcaliani requested changes

2022-04-22 19:45 UTC, lcaliani commented on src/api/mock/index.js
> +   * @returns {Promisse}
Promisse -> Promise

2022-04-22 19:45 UTC, lcaliani commented on src/plugins/http/index.js
> +export const httpBasic = axios.create({
Acredito que vale a pena uma descrição aqui, ex, 

> Client básico para requisições fora da rota `/checkout`

2022-04-22 19:45 UTC, lcaliani commented on src/screens/Login/screens/Main.vue
> +          payloadPost.endpoint = 'my-account/api/login';
Sugestão, separar essa rota em uma constante centralizada, para caso mudar um dia, não fique atrelada ao método

2022-04-23 01:28 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
> +          payloadPost.endpoint = 'my-account/api/login';
coloquei como uma função computada, o que acha?

2022-04-28 16:06 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
> +          console.log(JSON.stringify(payloadPost));
removido

2022-04-28 18:19 UTC, phmHubess commented on src/screens/Login/screens/Main.vue
> +     * Valida de callbackPost é diferente de "/"
erro de gramatica, deveria ser:
```suggestion
     * Valida se o callbackPost é diferente de "/"
```

2022-04-28 18:26 UTC, phmHubess commented on src/screens/Login/screens/Main.vue
> +          payloadPost.endpoint = this.payloadPostEndpoint;
```suggestion
          token = response.data.data.token;
          endpoint = this.payloadPostEndpoint;
```

2022-04-28 18:30 UTC, phmHubess commented on src/screens/Login/screens/Main.vue
>            this.redirect(this.callback, response.data.data.token);
teria como desestruturar esse `response.data.data.token`?

2022-04-28 19:38 UTC, gustavohubess commented on src/screens/Login/screens/Main.vue
>            this.redirect(this.callback, response.data.data.token);
feito

2022-04-28 19:40 UTC, merged