commerce/central#545 - Login com facebook
tray-tecnologia/tray-login pull request #136
Opened 2022-05-13 14:32 UTC by gustavohubess

[LINK DA ISSUE #545](https://git.tray.net.br/commerce/central/-/issues/545)

Foi adicionado o post de login ao fluxo do facebook. Ao realizar o login com o facebook, é retornado o token para realizar o login.

**Login com facebook**

![loginfacebookanonimo](https://user-images.githubusercontent.com/87497961/168305118-5a453b02-dec3-48d8-8767-bcdfd6bf7ff2.gif)

**PENDENCIA**

Caso o usuário *não* tenha o e-mail do facebook já cadastrado na loja, não é possivel efetuar o login. A equipe de design está trabalhando na tratativa desse cenário.
Enquanto a solução não é tratada, o usuário é redirecionado para a tela de login.

**Erro de e-mail do facebook não cadastrado**

![loginfacebookerro](https://user-images.githubusercontent.com/87497961/168305737-eac47395-b0e4-43fa-a2ef-cc748c980182.gif)

2022-05-13 17:05 UTC, lcaliani requested changes

2022-05-13 17:05 UTC, lcaliani commented on src/components/FacebookLogin.vue
> +     * Valida se há token no objeto de parametros
Adicionar na doc o parâmetro da função

2022-05-13 17:05 UTC, lcaliani commented on src/mixins/utils.js
> +      return `/${window.location.pathname.split('/')[1]}`;
Caso por algum motivo a url vir sem `/`, essa linha não poderá lançar um erro?

Talvez vale a pena validarmos esse cenário e fazer algum tratamento, se fizer sentido

2022-05-13 17:09 UTC, phmHubess commented on src/components/FacebookLogin.vue
> +     * Verifica se há tem callback tem tamanho
erro de gramatica

2022-05-13 17:53 UTC, gustavohubess commented on src/components/FacebookLogin.vue
> +     * Verifica se há tem callback tem tamanho
alterei para 
`Verifica se o tamanho da variavél de callback é maior que 0`

2022-05-13 17:53 UTC, gustavohubess commented on src/components/FacebookLogin.vue
> +     * Valida se há token no objeto de parametros
Adicionado:
`@param {object} objectParams objeto com os parametros de post`

2022-05-13 17:54 UTC, gustavohubess commented on src/components/FacebookLogin.vue
> +     * Verifica se há tem callback tem tamanho
alterei para
`Verifica se o tamanho da variavél de callback é maior que 0`

2022-05-13 18:01 UTC, gustavohubess commented on src/App.vue
> +     * Verifica se o login o login foi feito pelo facebook e se há token
Alterei para
`Verifica se o login foi feito pelo facebook e se há token de sessão`

2022-05-13 20:22 UTC, gustavohubess commented on src/mixins/utils.js
> +      return `/${window.location.pathname.split('/')[1]}`;
A função `homePath()` deve retornar o caminho referente ao ambiente em que está sendo usado o tray-login. As opções de caminho possíveis são `/stg-my-account`, `/stg1-my-account`, `/stg2-my-account` ou `/stg3-my-account`. Para validar esse fluxo, foram feitas as seguintes alterações:

Foi adicionada a variável `pathEnvironment` que recebe o valor do caminho de acordo com o ambiente:
![image](https://user-images.githubusercontent.com/87497961/168383565-1f8a05bb-f5ac-43ed-92d6-272dd11b22ef.png)

Para validar se o caminho corresponde a uma dessas opções validas, foi criada a função `isValidPath`:
![image](https://user-images.githubusercontent.com/87497961/168383392-8307be14-870e-4863-afab-4e02a7debc4a.png)

Essa foi adicionada ao `homePath()` para evitar que receba um caminho errado:
![image](https://user-images.githubusercontent.com/87497961/168383470-0f403c15-d2f6-4870-9edc-5a307891fa5a.png)

2022-05-16 12:44 UTC, gustavohubess commented on src/mixins/utils.js
> +      return `/${window.location.pathname.split('/')[1]}`;
Atualização

Foi simplificada a lógica da função `isValidPath()`
![image](https://user-images.githubusercontent.com/87497961/168595077-8b597bfe-e8a7-4997-90bd-8ff87d3b1d15.png)

2022-05-16 14:33 UTC, merged